# Generated by Django 3.0.2 on 2020-02-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20200213_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelciudad',
            name='poblacion',
        ),
    ]
